name: xMemory
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - blas=2.136=openblas
  - blas-devel=3.9.0=36_h1ea3ea9_openblas
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - catalogue=2.0.10=py311h38be061_2
  - certifi=2025.8.3=pyhd8ed1ab_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - cloudpathlib=0.22.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - confection=0.1.5=pyhecae5ae_0
  - cymem=2.0.11=py311hbdd6827_0
  - cython-blis=1.0.1=py311h5eee18b_0
  - expat=2.7.1=h6a678d5_0
  - idna=3.10=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - language-data=1.3.0=pyhff2d567_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libblas=3.9.0=36_h4a7cf45_openblas
  - libcblas=3.9.0=36_h0358290_openblas
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=36_h47877c9_openblas
  - liblapacke=3.9.0=36_h6ae95b6_openblas
  - libopenblas=0.3.30=h46f56fc_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - marisa-trie=1.3.1=py311hbdd6827_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nomkl=3.0=0
  - numpy=2.3.3=py311hc213724_0
  - numpy-base=2.3.3=py311hf387b04_0
  - openblas=0.3.30=h5426c36_0
  - openblas-devel=0.3.30=h557178c_0
  - openssl=3.0.17=h5eee18b_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pydantic=2.11.9=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py311hc6f7160_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.13=h1a3bd86_0
  - python_abi=3.11=2_cp311
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhd8ed1ab_0
  - setuptools=70.3.0=pyhd8ed1ab_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - smart-open=7.3.1=h08b120a_0
  - smart_open=7.3.1=pyhcf101f3_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.5=pyhd8ed1ab_0
  - spacy-model-en_core_web_sm=3.8.0=pyhd8ed1ab_0
  - spacy-model-zh_core_web_sm=3.8.0=pyhd8ed1ab_0
  - spacy-pkuseg=1.0.0=py311hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - srsly=2.5.1=py311h6a678d5_0
  - tk=8.6.15=h54e0aa7_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wasabi=1.1.3=pyhd8ed1ab_1
  - weasel=0.4.1=pyhd8ed1ab_2
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aiofiles==24.1.0
      - anyio==4.11.0
      - attrs==25.3.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - bert-score==0.3.13
      - blis==1.3.0
      - build==1.3.0
      - cachetools==5.5.2
      - chromadb==1.1.0
      - coloredlogs==15.0.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - distro==1.9.0
      - durationpy==0.10
      - faiss-cpu==1.12.0
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.60.0
      - fsspec==2025.9.0
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0
      - grpcio==1.75.1
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.35.2
      - humanfriendly==10.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jiter==0.11.0
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - kubernetes==33.1.0
      - langcodes==3.5.0
      - llmlingua==0.2.2
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - mmh3==5.2.0
      - mpmath==1.3.0
      - murmurhash==1.0.13
      - networkx==3.5
      - nltk==3.9.1
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.3.1
      - onnxruntime==1.23.0
      - openai==2.14.0
      - opentelemetry-api==1.37.0
      - opentelemetry-exporter-otlp-proto-common==1.37.0
      - opentelemetry-exporter-otlp-proto-grpc==1.37.0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - orjson==3.11.3
      - overrides==7.7.0
      - pandas==2.3.2
      - pillow==11.3.0
      - posthog==5.4.0
      - preshed==3.0.10
      - protobuf==6.32.1
      - psutil==7.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pyparsing==3.2.5
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - rank-bm25==0.2.2
      - referencing==0.36.2
      - regex==2025.9.18
      - requests-oauthlib==2.0.0
      - rich==14.1.0
      - rouge-score==0.1.2
      - rpds-py==0.27.1
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - sentence-transformers==5.1.1
      - six==1.17.0
      - sniffio==1.3.1
      - spacy==3.8.7
      - sympy==1.14.0
      - tenacity==9.1.2
      - thinc==8.3.6
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - torch==2.8.0
      - transformers==4.56.2
      - triton==3.4.0
      - typer==0.19.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - uvloop==0.21.0
      - watchfiles==1.1.0
      - websocket-client==1.8.0
      - websockets==15.0.1
      - wrapt==1.17.3
      - zipp==3.23.0
